[package]
org = "solarshare"
name = "auth_service"
version = "0.1.0"
distribution = "2201.8.5"

[build-options]
observabilityIncluded = true

[[dependency]]
org = "ballerina"
name = "http"
version = "2.10.10"

[[dependency]]
org = "ballerina"
name = "crypto"
version = "2.7.0"

[[dependency]]
org = "ballerina"
name = "uuid"
version = "2.5.0"

[[dependency]]
org = "ballerinax"
name = "mongodb"
version = "3.0.0"