[package]
org = "solarshare"
name = "auth_service"
version = "0.1.0"
distribution = "2201.8.5"

[build-options]
observabilityIncluded = true

[[dependency]]
org = "ballerina"
name = "http"
version = "2.10.10"

[[dependency]]
org = "ballerina"
name = "jwt"
version = "2.10.0"

[[dependency]]
org = "ballerina"
name = "crypto"
version = "2.7.0"

[[dependency]]
org = "ballerina"
name = "time"
version = "2.4.0"

[[dependency]]
org = "ballerina"
name = "log"
version = "2.9.0"